title: PARASOL MEMO
description: Personal film photography archive
baseurl: ""
url: ""
collections:
  works:
    output: true
    permalink: /work/:name/
defaults:
  - scope:
      path: ""
      type: works
    values:
      layout: work
      published: true
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /journal/:year/:month/:day/:title/
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
