title: PARASOL MEMO

baseurl: "/parasolmemo"
url: "https://utofuya.github.io"

markdown: kramdown

collections:
  works:
    output: true
    permalink: /works/:name/

defaults:
  - scope:
      path: ""
      type: works
    values:
      layout: work
